env:
 global:
   - "ARTIFACTS_AWS_REGION=Oregon"
   - "ARTIFACTS_S3_BUCKET=auguronomics"
   - "ARTIFACTS_AWS_ACCESS_KEY_ID=AKIAJLON7XK2LUHMV3ZA"
   - "ARTIFACTS_AWS_SECRET_ACCESS_KEY=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"
language: java
before_install:
  - "./gradlew -version"
install: "./gradlew assemble"
script: "./gradlew clean fastbuild"
jdk:
  - oraclejdk7
  - oraclejdk8
after_success:
  - "./gradlew bundle"
# the next line is a workaround for https://github.com/travis-ci/travis-artifacts/issues/23
  - "gem install --version 0.8.9 faraday"
  - "gem install travis-artifacts"
  - "travis-artifacts upload --path zips --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
